#!/bin/bash
set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "$SCRIPT_DIR/common.sh"

echo ""
echo "╔══════════════════════════════════════════════════════════════╗"
echo "║          🚀  Codespace Setup — Starting                      ║"
echo "╚══════════════════════════════════════════════════════════════╝"
echo ""
echo "📁  Repository root: $REPO_ROOT"
echo ""

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "🐍  Step 1/4: Python environment setup"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
bash "$SCRIPT_DIR/install-python.sh"

echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "🤖  Step 2/4: Claude Code CLI"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
bash "$SCRIPT_DIR/configure-claude.sh"

echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "⚙️   Step 3/4: Environment configuration"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
bash "$REPO_ROOT/scripts/configure-env.sh"

echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "🩺  Step 4/4: Health check"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
bash "$REPO_ROOT/scripts/health-check.sh" || true

echo ""
echo "╔══════════════════════════════════════════════════════════════╗"
echo "║          ✅  Codespace Setup — Complete!                     ║"
echo "╚══════════════════════════════════════════════════════════════╝"
echo ""
echo "  Available commands:"
echo ""
echo "    make jupyter        → Start Jupyter Lab on port 8888"
echo "    make test           → Run pytest with coverage"
echo "    make lint           → Run black + pylint"
echo "    make docker-up      → Start Postgres + Redis containers"
echo "    make install-core   → Install core packages only"
echo "    make install-ml     → Install ML/DL packages"
echo "    make install-extras → Install OCR/scraping/DB packages"
echo "    make pin-deps       → Lock package versions with pip-compile"
echo "    claude              → Open Claude Code AI assistant"
echo ""
echo "  Python info:"
echo "    python --version    → $(python --version 2>&1)"
echo "    pyenv versions      → List all installed Python versions"
echo ""
